name: Crear App para Mac
on: [push] # Se activa cada vez que subes algo

jobs:
  build:
    runs-on: macos-latest # ¡Aquí pedimos la Mac virtual!
    steps:
    - uses: actions/checkout@v4
    
    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Instalar Librerias
      run: |
        pip install python-docx psutil pyinstaller
        
    - name: Construir Ejecutable
      run: |
        # Esto crea el archivo de Mac
        pyinstaller --onefile --windowed --name "Escaneo_Mac" reporte_pc.py
        
    - name: Guardar Resultado
      uses: actions/upload-artifact@v4
      with:
        name: App-Mac-Lista
        path: dist/Escaneo_Mac.app
