name: Crear App para Mac
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Listar archivos para verificar (Debug)
        run: ls -R

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Librerias
        run: |
          pip install python-docx psutil pyinstaller

      - name: Construir App de Mac
        run: |
          # Si tu archivo tiene otro nombre, cámbialo aquí abajo:
          pyinstaller --onefile --windowed --name "Escaneo_Mac" --noconfirm reporte_pc.py

      - name: Guardar y Generar Descarga
        uses: actions/upload-artifact@v4
        with:
          name: App-Mac-Lista
          path: dist/Escaneo_Mac.app
